
services:
  technical-challenge-of-picpay:
    container_name: technical-challenge-of-picpay
    image: technical-challenge-of-picpay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5132:80"
    environment:
      ConnectionStrings__DefaultConnection: "User ID=postgres;Password=@1618;Host=localhost;Port=5432;Database=Transacoes;Pooling=true;Connection Lifetime=0;"
    depends_on:
      - postgres
  postgres:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: @1618
      POSTGRES_USER: postgres
      POSTGRES_DB: Transacoes
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: { }